### ISSUE TITLE
solution from Assignment 5 is not working 

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [JeffreyATW/fwd#2]
The solutions links for Assignments 1-4 work perfectly, however, Assignment # 5 does not display a pop up solution. Only the click here to ask a question displays.

**Comment by JeffreyATW** [comment]
Series 9? It works for me - the code to make the "click here" text work is intentionally commented out.

**Comment by Karla-Isabel-Sandoval** [comment]
Just double checked it, and you are right, it is working. Sorry about the confusion.
